import { PlexityLogic } from './PlexityLogic.js';

/**
 * Resonance Field Plexity
 * Dictates the "bling-bling" graphics intensity generated by string logic.
 */
export class ResonanceFieldPlexity {
    /**
     * Translates pure boolean resonance into graphic intensity multipliers.
     */
    static computeBlingFactor(isResonant: boolean, zoneId: string): number {
        if (!isResonant) return 0.0;

        const basePlexity = PlexityLogic.calculateComplexity(zoneId);

        // Lexicographical values determine visual frequency
        const lexicographicalValue = zoneId.charCodeAt(0) % 10;

        const blingIntensity = basePlexity + (lexicographicalValue / 10);

        return Math.min(blingIntensity, 1.0);
    }
}
