version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "reviewer-name"
    labels:
      - "dependencies"
      - "npm"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "reviewer-name"
    labels:
      - "dependencies"
      - "docker"