apply plugin: 'com.android.application'

android {
    namespace 'com.ouroboros.arelorian'
    compileSdk 33

    defaultConfig {
        applicationId "com.ouroboros.arelorian"
        minSdk 22
        targetSdk 33
        versionCode 1
        versionName "1.0.0"
        
        multiDexEnabled true
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled false
            debuggable true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    packagingOptions {
        resources {
            excludes += ['META-INF/NOTICE.md', 'META-INF/LICENSE.md']
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.core:core-ktx:1.10.1'
    implementation 'androidx.activity:activity:1.7.2'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation project(':capacitor-android')
}