packages:
  - "packages/*"
  - "packages/sdk-examples/*"
  - "apps/*"
  - "projects/*"
  - "client"
  - "engine"
  - "portal"
  - "server"
  - "backend"
allowBuilds:
  '@firebase/util': true
  '@google/genai': true
  '@nestjs/core': true
  '@prisma/client': set this to true or false
  '@prisma/engines': true
  cpu-features: true
  esbuild: true
  pg: set this to true or false
  prisma: true
  protobufjs: true
  ssh2: true
