/**
 * EQUIPMENT STAT SERVICE
 *
 * Server-authoritative aggregation of equipment stats.
 * Calculates the total stat bonuses from all equipped items.
 *
 * Rules:
 * - Only equipped items count toward stats
 * - Starter tools retain their Tier bonus
 * - Procedural items count via mapped stats
 * - Unknown item IDs are ignored or use safe defaults
 * - Deterministic: sorted by slot ID
 * - No mutation of source data
 * - No Math.random(), no Date.now()
 */

import type { PlayerEquipmentState, EquippedSlot } from "./EquipmentTypes.js";
import { EQUIPMENT_DEFINITIONS } from "./EquipmentTypes.js";
import type {
  EquipmentStatBlock,
  EquipmentStatKey,
} from "./EquipmentStatTypes.js";
import {
  createDefaultStatBlock,
  statKeyToPropertyName,
  isEquipmentStatKey,
  capStatValue,
  EQUIPMENT_STAT_CAPS,
} from "./EquipmentStatTypes.js";
import { mapAffixToEquipmentStat } from "./AffixStatMapping.js";

/**
 * Options for calculating equipment stats.
 */
export interface CalculateEquipmentStatsOptions {
  /** Player equipment state with equipped slots */
  equipment: PlayerEquipmentState;
  /**
   * Optional map of procedural loot item IDs to their stats.
   * Used for items generated by the ProceduralLootMachine.
   * Key: item ID (string), Value: array of {key, value} stats
   */
  proceduralItemStats?: ReadonlyMap<string, ReadonlyArray<{ key: string; value: number }>>;
}

/**
 * Calculate the total equipment stat block from all equipped items.
 *
 * @param options - Equipment state and optional procedural item stats
 * @returns Aggregated EquipmentStatBlock with all bonuses
 */
export function calculateEquipmentStats(options: CalculateEquipmentStatsOptions): EquipmentStatBlock {
  const { equipment, proceduralItemStats } = options;
  const aggregated: Record<string, number> = {};

  // Process each equipped slot
  // Bolt: Optimized equipment slot sorting using fast direct relational string comparisons instead of slow localeCompare
  const sortedSlots = [...equipment.slots].sort((a, b) => (a.slotId < b.slotId ? -1 : a.slotId > b.slotId ? 1 : 0));

  for (const slot of sortedSlots) {
    // Check if this is a known gathering tool definition
    const definition = EQUIPMENT_DEFINITIONS[slot.itemId];
    if (definition) {
      // Gathering tools use tier-based bonuses (handled elsewhere)
      // They don't contribute via the stats mapping system
      continue;
    }

    // Check if this is a procedural loot item with stats
    if (proceduralItemStats && proceduralItemStats.has(slot.itemId)) {
      const itemStats = proceduralItemStats.get(slot.itemId)!;
      aggregateItemStats(aggregated, itemStats);
      continue;
    }

    // Fallback: check if the slot itself has inline stats
    if (slot.stats) {
      aggregateItemStats(aggregated, slot.stats);
    }
  }

  // Build the result block, applying caps
  return buildStatBlock(aggregated);
}

/**
 * Aggregate item stats into the running total.
 * Unknown stat keys are ignored.
 */
function aggregateItemStats(
  aggregated: Record<string, number>,
  itemStats: ReadonlyArray<{ key: string; value: number }>,
): void {
  for (const stat of itemStats) {
    if (!isEquipmentStatKey(stat.key)) {
      continue;
    }
    const current = aggregated[stat.key] ?? 0;
    aggregated[stat.key] = current + stat.value;
  }
}

/**
 * Build a stat block from aggregated stats, applying caps.
 */
function buildStatBlock(aggregated: Record<string, number>): EquipmentStatBlock {
  const result = createDefaultStatBlock();
  const capped: EquipmentStatBlock = { ...result };

  for (const [key, value] of Object.entries(aggregated)) {
    if (!isEquipmentStatKey(key)) {
      continue;
    }
    const propertyName = statKeyToPropertyName(key);
    const cappedValue = capStatValue(key, value);
    (capped as any)[propertyName] = cappedValue;
  }

  return Object.freeze(capped);
}

/**
 * Get stats from a single equipped item.
 * Used for tooltip display.
 */
export function getItemStats(itemId: string): ReadonlyArray<{ key: EquipmentStatKey; value: number }> {
  const stats: Array<{ key: EquipmentStatKey; value: number }> = [];

  // Check gathering tool definitions
  const definition = EQUIPMENT_DEFINITIONS[itemId];
  if (definition) {
    // Gathering tools don't have stats via this system
    return Object.freeze(stats);
  }

  // Unknown item - return empty
  return Object.freeze(stats);
}

/**
 * Check if an item has equipment stats.
 */
export function itemHasStats(itemId: string): boolean {
  // Gathering tools have bonuses but via tier system
  const definition = EQUIPMENT_DEFINITIONS[itemId];
  if (definition) {
    return false;
  }
  // For procedural items, we'd need to check against proceduralItemStats
  // This function is mainly for known static items
  return false;
}

/**
 * Merge two stat blocks together.
 * Used when combining base player stats with equipment bonuses.
 */
export function mergeStatBlocks(
  base: EquipmentStatBlock,
  equipment: EquipmentStatBlock,
): EquipmentStatBlock {
  return Object.freeze({
    attackPower: base.attackPower + equipment.attackPower,
    defense: base.defense + equipment.defense,
    maxHealth: base.maxHealth + equipment.maxHealth,
    maxStamina: base.maxStamina + equipment.maxStamina,
    magicFind: base.magicFind + equipment.magicFind,
    gatheringYield: base.gatheringYield + equipment.gatheringYield,
    gatheringXp: base.gatheringXp + equipment.gatheringXp,
    lootQuality: base.lootQuality + equipment.lootQuality,
    criticalChancePerMille: base.criticalChancePerMille + equipment.criticalChancePerMille,
  });
}

/**
 * Calculate the effective magic find for loot generation.
 * Combines base magic find (from character) with equipment magic find.
 *
 * Note: The RarityResolver receives magicFind as a flat value.
 * This function helps compute the total effective magic find.
 */
export function calculateEffectiveMagicFind(
  baseMagicFind: number,
  equipmentMagicFind: number,
): number {
  // Simple addition for MVP
  // In future, could apply diminishing returns formula
  const total = baseMagicFind + equipmentMagicFind;
  return Math.min(EQUIPMENT_STAT_CAPS.magic_find, Math.max(0, total));
}

/**
 * Calculate the effective gathering yield bonus.
 * Combines tool tier bonus with equipment gathering yield.
 *
 * @param toolTierBonus - Base yield from tool tier (0 for no tool, 1 for tier 1, etc.)
 * @param equipmentGatheringYield - Equipment gathering yield stat
 * @returns Total gathering yield bonus (capped at 5)
 */
export function calculateEffectiveGatheringYield(
  toolTierBonus: number,
  equipmentGatheringYield: number,
): number {
  const total = toolTierBonus + equipmentGatheringYield;
  return Math.min(EQUIPMENT_STAT_CAPS.gathering_yield, Math.max(0, total));
}