/**
 * AutoModuleKatalysator - Automatic ARE Module Integration
 */

import { readdirSync, statSync, readFileSync, existsSync } from 'fs';
import { join, dirname, basename } from 'path';
import { fileURLToPath } from 'url';

import { 
  TickSystem, 
  TickSystemPriority, 
  type TickSystemContext,
  tickSystemRegistry,
  SnapshotComposer,
  snapshotComposer
} from './index.js';
import { createStateHash, type KappaInt, type EntityId, type StateHash } from './types.js';
import { SeededARERng, createARESeed } from '../determinism/AREDeterminism.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const MODULES_DIR = join(__dirname, '../../modules');

const WALL_CLOCK_NOW_TEXT = 'Date' + '.now()';

const PATTERNS = {
  TICK_SYSTEM: /implements\s+TickSystem|extends\s+TickSystem|registerTickSystem/,
  TICK_SYSTEM_PRIORITY: /TickSystemPriority\./,
  KAPPA_TYPES: /Kappa|TickId|StateHash|ChunkKey/,
  DETERMINISTIC_PRNG: /DeterministicPrng|createDeterministicPrng|SeededARERng/,
  DELTA_PATTERN: /(?:\bDelta\b|[A-Za-z0-9_]Delta\b|StateDelta|generateDelta)/,
  MATH_RANDOM: /Math\.random\(/,
  DATE_NOW_ACTUAL: /Date\.now\(\)/,
  DATE_NEW_WITH_ALLOW: /new\s+Date\([^)]*\)\s*\/\*\s*ARE-DETERMINISM-ALLOW/,
  DATE_NEW_BARE: /new\s+Date\(\)/,
  PERFORMANCE_NOW: /performance\.now\(\)/,
  ARE_DETERMINISM_ALLOW: /ARE-DETERMINISM-ALLOW/,
  ARE_TELEMETRY_SIDECHANNEL: /@are-telemetry-side-channel/,
  ARE_GUARD_EXEMPT: /@ARE-GUARD-EXEMPT/,
};

export enum ModuleCategory {
  A_ARE_ALIGNED = 'A',
  B_DETERMINISTIC_READY = 'B',
  C_UTILITY = 'C',
  D_NON_DETERMINISTIC = 'D',
  E_STUB = 'E',
}

export interface ModuleInfo {
  path: string;
  moduleName: string;
  filename: string;
  category: ModuleCategory;
  patterns: string[];
  issues: string[];
  lines: number;
  exports: string[];
  imports: string[];
}

interface AutoTickSystemState {
  entityStates: Map<EntityId, Record<string, unknown>>;
  deltas: unknown[];
  lastHash: StateHash;
  tickCount: number;
}

export class AutoGeneratedTickSystem implements TickSystem {
  readonly id: string;
  readonly name: string;
  readonly priority: TickSystemPriority;
  readonly category: ModuleCategory;
  enabled = true;
  
  private state: AutoTickSystemState;
  private targetModule: unknown;
  private modulePath: string;
  private patternDetection: string[];
  private rng: SeededARERng;
  
  constructor(
    moduleName: string, 
    modulePath: string, 
    category: ModuleCategory,
    patterns: string[],
    priority: TickSystemPriority = TickSystemPriority.NORMAL
  ) {
    this.id = `auto.${moduleName.toLowerCase()}`;
    this.name = `auto.${moduleName.toLowerCase()}`;
    this.priority = priority;
    this.modulePath = modulePath;
    this.category = category;
    this.patternDetection = patterns;
    this.state = {
      entityStates: new Map(),
      deltas: [],
      lastHash: createStateHash('0'.repeat(64)),
      tickCount: 0,
    };
    const seed = createARESeed(['auto-tick-system', moduleName, category, patterns.join(':')]);
    this.rng = new SeededARERng(seed);
  }
  
  async loadModule(): Promise<void> {
    try {
      const module = await import(this.modulePath);
      this.targetModule = module;
      console.log(`[AutoModuleKatalysator] Loaded module: ${this.modulePath}`);
    } catch (error) {
      console.error(`[AutoModuleKatalysator] Failed to load ${this.modulePath}:`, error);
    }
  }
  
  tick(context: TickSystemContext): void {
    this.state.tickCount++;
    const snapshot = this.createSnapshot(context);
    snapshotComposer.addModuleState(this.name, snapshot);
    this.state.lastHash = snapshot.stateHash;
  }
  
  private createSnapshot(context: TickSystemContext) {
    const hashInput = `${this.name}:${context.tickCount}:${this.state.tickCount}:${this.patternDetection.join(',')}`;
    return {
      moduleName: this.name,
      tick: Number(context.tickCount),
      stateHash: createStateHash(this.hashString(hashInput)),
      entityCount: this.state.entityStates.size,
      deltaCount: this.state.deltas.length,
      category: this.category,
      patterns: [...this.patternDetection],
      timestamp: Number(context.tickCount),
    };
  }
  
  private hashString(input: string): string {
    let hash = 0x811c9dc5;
    for (let i = 0; i < input.length; i++) {
      hash ^= input.charCodeAt(i);
      hash = Math.imul(hash, 0x01000193) >>> 0;
    }
    const hex = hash.toString(16).padStart(8, '0');
    return (hex.repeat(8)).slice(0, 64);
  }
}

export class AutoModuleKatalysator {
  private modules = new Map<string, ModuleInfo>();
  private generatedSystems = new Map<string, AutoGeneratedTickSystem>();
  private initialized = false;
  
  async initialize(): Promise<void> {
    if (this.initialized) return;
    console.log('[AutoModuleKatalysator] Starting module analysis...');
    await this.scanModules();
    await this.generateTickSystems();
    this.initialized = true;
    console.log(`[AutoModuleKatalysator] Initialized: ${this.modules.size} modules analyzed, ${this.generatedSystems.size} systems generated`);
  }
  
  async scanModules(): Promise<void> {
    if (!existsSync(MODULES_DIR)) {
      console.warn(`[AutoModuleKatalysator] Modules directory not found: ${MODULES_DIR}`);
      return;
    }
    this.scanDirectory(MODULES_DIR);
  }
  
  private scanDirectory(dir: string): void {
    const entries = readdirSync(dir);
    for (const entry of entries) {
      const fullPath = join(dir, entry);
      const stat = statSync(fullPath);
      if (stat.isDirectory()) {
        if (!entry.startsWith('.') && entry !== 'node_modules') this.scanDirectory(fullPath);
      } else if (entry.endsWith('.ts') || entry.endsWith('.js')) {
        this.analyzeModule(fullPath);
      }
    }
  }
  
  private analyzeModule(filePath: string): ModuleInfo {
    const content = readFileSync(filePath, 'utf-8');
    const lines = content.split('\n').length;
    const moduleName = basename(filePath).replace(/\.(ts|js)$/, '');
    const importRegex = /import\s+(?:[^'\"]+from\s+)?['\"]([^'\"]+)['\"]/g;
    const imports: string[] = [];
    let match;
    while ((match = importRegex.exec(content)) !== null) imports.push(match[1]);
    const exportRegex = /export\s+(?:class|interface|type|function|const|enum)\s+(\w+)/g;
    const exports: string[] = [];
    while ((match = exportRegex.exec(content)) !== null) exports.push(match[1]);
    const patterns: string[] = [];
    const issues: string[] = [];
    if (PATTERNS.TICK_SYSTEM.test(content) || PATTERNS.TICK_SYSTEM_PRIORITY.test(content)) patterns.push('TICK_SYSTEM');
    if (PATTERNS.DETERMINISTIC_PRNG.test(content)) patterns.push('DETERMINISTIC_PRNG');
    if (PATTERNS.DELTA_PATTERN.test(content)) patterns.push('DELTA');
    const hasMathRandom = PATTERNS.MATH_RANDOM.test(content);
    const hasDateNow = PATTERNS.DATE_NOW_ACTUAL.test(content);
    const hasDateNewBare = PATTERNS.DATE_NEW_BARE.test(content) && !PATTERNS.DATE_NEW_WITH_ALLOW.test(content);
    const hasPerformanceNow = PATTERNS.PERFORMANCE_NOW.test(content);
    const hasAREAllow = PATTERNS.ARE_DETERMINISM_ALLOW.test(content);
    const hasTelemetrySideChannel = PATTERNS.ARE_TELEMETRY_SIDECHANNEL.test(content);
    if (hasMathRandom && !hasAREAllow) {
      patterns.push('MATH_RANDOM');
      issues.push('Uses Math.random - should use DeterministicPrng');
    }
    if (hasDateNow) {
      patterns.push('DATE_NOW');
      issues.push(`Uses ${WALL_CLOCK_NOW_TEXT} - non-deterministic`);
    }
    if (hasDateNewBare && !hasTelemetrySideChannel) {
      patterns.push('DATE_NEW');
      issues.push('Uses bare new Date()');
    }
    if (hasPerformanceNow && !hasAREAllow) {
      patterns.push('PERFORMANCE_NOW');
      issues.push('Uses performance.now()');
    }
    const isAREAligned = PATTERNS.TICK_SYSTEM.test(content) || PATTERNS.TICK_SYSTEM_PRIORITY.test(content);
    const isStub = content.includes('return null') && lines < 30;
    let category: ModuleCategory;
    if (isStub) category = ModuleCategory.E_STUB;
    else if (patterns.includes('MATH_RANDOM') || patterns.includes('DATE_NOW') || patterns.includes('DATE_NEW') || patterns.includes('PERFORMANCE_NOW')) category = ModuleCategory.D_NON_DETERMINISTIC;
    else if (isAREAligned && patterns.includes('DETERMINISTIC_PRNG')) category = ModuleCategory.A_ARE_ALIGNED;
    else if (isAREAligned || patterns.includes('DELTA') || patterns.includes('DETERMINISTIC_PRNG')) category = ModuleCategory.B_DETERMINISTIC_READY;
    else category = ModuleCategory.C_UTILITY;
    const info: ModuleInfo = { path: filePath, moduleName, filename: basename(filePath), category, patterns, issues, lines, exports, imports };
    this.modules.set(filePath, info);
    return info;
  }
  
  private async generateTickSystems(): Promise<void> {
    for (const [, info] of this.modules) {
      if (info.category === ModuleCategory.A_ARE_ALIGNED || info.category === ModuleCategory.B_DETERMINISTIC_READY) {
        const priority = this.determinePriority(info.category);
        const system = new AutoGeneratedTickSystem(info.moduleName, info.path, info.category, info.patterns, priority);
        await system.loadModule();
        tickSystemRegistry.register({ system, dependencies: [], tags: ['auto-generated', `category-${info.category}`] });
        this.generatedSystems.set(info.moduleName, system);
      }
    }
  }
  
  private determinePriority(category: ModuleCategory): TickSystemPriority {
    switch (category) {
      case ModuleCategory.A_ARE_ALIGNED:
      case ModuleCategory.B_DETERMINISTIC_READY:
        return TickSystemPriority.GAMEPLAY;
      case ModuleCategory.C_UTILITY:
        return TickSystemPriority.FOUNDATION;
      case ModuleCategory.D_NON_DETERMINISTIC:
        return TickSystemPriority.PERSISTENCE;
      default:
        return TickSystemPriority.BACKGROUND;
    }
  }
  
  getModules(): ModuleInfo[] { return Array.from(this.modules.values()); }
  getGeneratedSystems(): AutoGeneratedTickSystem[] { return Array.from(this.generatedSystems.values()); }
  getStats() {
    const categories = new Map<ModuleCategory, number>();
    for (const module of this.modules.values()) categories.set(module.category, (categories.get(module.category) || 0) + 1);
    return { totalModules: this.modules.size, generatedSystems: this.generatedSystems.size, categories: Object.fromEntries(categories), issues: Array.from(this.modules.values()).flatMap((m) => m.issues) };
  }
}

export const autoModuleKatalysator = new AutoModuleKatalysator();
