/**
 * AutoModuleKatalysator - Automatic ARE Module Integration
 * 
 * Phase 2 of the ARE Module Standard initiative.
 * 
 * This system automatically:
 * 1. Scans all modules in server/src/modules/ at startup
 * 2. Identifies Category B modules (Deterministic-Ready)
 * 3. Auto-generates TickSystem wrappers at runtime
 * 4. Registers modules with TickSystemRegistry
 * 5. Couples outputs to SnapshotComposer for PixiJS client
 * 
 * Usage:
 *   import { autoModuleKatalysator } from './AutoModuleKatalysator';
 *   await autoModuleKatalysator.initialize();
 */

import { readdirSync, statSync, readFileSync, existsSync } from 'fs';
import { join, dirname, basename } from 'path';
import { fileURLToPath } from 'url';

import { 
  TickSystem, 
  TickSystemPriority, 
  type TickSystemContext,
  tickSystemRegistry,
  SnapshotComposer,
  snapshotComposer
} from './index.js';
import { createStateHash, type KappaInt, type EntityId, type StateHash } from './types.js';
import { SeededARERng, createARESeed } from '../determinism/AREDeterminism.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const MODULES_DIR = join(__dirname, '../../modules');

// ============================================================================
// Module Classification Patterns
// ============================================================================

const PATTERNS = {
  // ARE-aligned patterns (Category A)
  TICK_SYSTEM: /implements\s+TickSystem|extends\s+TickSystem|registerTickSystem/,
  TICK_SYSTEM_PRIORITY: /TickSystemPriority\./,
  KAPPA_TYPES: /Kappa|TickId|StateHash|ChunkKey/,
  DETERMINISTIC_PRNG: /DeterministicPrng|createDeterministicPrng|SeededARERng/,
  DELTA_PATTERN: /\bDelta\b|StateDelta|generateDelta/,
  
  // Non-deterministic patterns (Category D)
  MATH_RANDOM: /Math\.random\(/,
  DATE_NOW_ACTUAL: /Date\.now\(\)/,
  DATE_NEW_WITH_ALLOW: /new\s+Date\([^)]*\)\s*\/\*\s*ARE-DETERMINISM-ALLOW/,
  DATE_NEW_BARE: /new\s+Date\(\)/,
  PERFORMANCE_NOW: /performance\.now\(\)/,
  
  // ARE annotations
  ARE_DETERMINISM_ALLOW: /ARE-DETERMINISM-ALLOW/,
  ARE_TELEMETRY_SIDECHANNEL: /@are-telemetry-side-channel/,
  ARE_GUARD_EXEMPT: /@ARE-GUARD-EXEMPT/,
};

// ============================================================================
// Module Category
// ============================================================================

export enum ModuleCategory {
  A_ARE_ALIGNED = 'A',        // Already follows TickSystem pattern
  B_DETERMINISTIC_READY = 'B', // Has game logic, needs ARE wrapping
  C_UTILITY = 'C',            // Math/Date utilities, generally safe
  D_NON_DETERMINISTIC = 'D',  // Uses Math.random/Date.now, needs refactoring
  E_STUB = 'E',              // No real logic, candidates for deletion
}

export interface ModuleInfo {
  path: string;
  moduleName: string;
  filename: string;
  category: ModuleCategory;
  patterns: string[];
  issues: string[];
  lines: number;
  exports: string[];
  imports: string[];
}

// ============================================================================
// Auto-Generated TickSystem Wrapper
// ============================================================================

interface AutoTickSystemState {
  entityStates: Map<EntityId, Record<string, unknown>>;
  deltas: unknown[];
  lastHash: StateHash;
  tickCount: number;
}

export class AutoGeneratedTickSystem implements TickSystem {
  readonly name: string;
  readonly priority: TickSystemPriority;
  enabled = true;
  
  private state: AutoTickSystemState;
  private targetModule: unknown;
  private modulePath: string;
  private category: ModuleCategory;
  private patternDetection: string[];
  private rng: SeededARERng;
  
  constructor(
    moduleName: string, 
    modulePath: string, 
    category: ModuleCategory,
    patterns: string[],
    priority: TickSystemPriority = TickSystemPriority.GAMEPLAY
  ) {
    this.name = `auto.${moduleName.toLowerCase()}`;
    this.priority = priority;
    this.modulePath = modulePath;
    this.category = category;
    this.patternDetection = patterns;
    
    // Initialize deterministic state
    this.state = {
      entityStates: new Map(),
      deltas: [],
      lastHash: createStateHash('0'.repeat(64)),
      tickCount: 0,
    };
    
    // Create deterministic RNG for this system
    const seed = createARESeed(['auto-tick-system', moduleName, category, patterns.join(':')]);
    this.rng = new SeededARERng(seed);
  }
  
  async loadModule(): Promise<void> {
    try {
      // Dynamic import of the target module
      const module = await import(this.modulePath);
      
      // Find the main export (class or factory function)
      const exports = Object.keys(module);
      const mainExport = exports.find(e => 
        e.includes(this.modulePath.split('/').pop()!.replace('.ts', '').split('/').pop()!) ||
        e.includes(basename(this.modulePath, '.ts'))
      );
      
      if (mainExport && module[mainExport]) {
        this.targetModule = module[mainExport];
      } else if (exports.length > 0 && typeof module[exports[0]] === 'function') {
        this.targetModule = module[exports[0]];
      }
      
      console.log(`[AutoModuleKatalysator] Loaded module: ${this.name} -> ${this.modulePath}`);
    } catch (error) {
      console.error(`[AutoModuleKatalysator] Failed to load module ${this.modulePath}:`, error);
      throw error;
    }
  }
  
  tick(context: TickSystemContext): void {
    const tickCount = context.tickCount;
    this.state.tickCount = tickCount;
    
    // Generate deterministic tick hash
    const tickSeed = createARESeed([
      this.name,
      tickCount,
      this.state.lastHash,
      this.category,
    ]);
    
    const tickRng = new SeededARERng(tickSeed);
    
    // Process based on module category
    switch (this.category) {
      case ModuleCategory.A_ARE_ALIGNED:
        // Already has TickSystem - delegate
        this.tickAREAlignedModule(context, tickRng);
        break;
        
      case ModuleCategory.B_DETERMINISTIC_READY:
        // Auto-wrap deterministic logic
        this.tickDeterministicReadyModule(context, tickRng);
        break;
        
      case ModuleCategory.C_UTILITY:
        // Process utility functions
        this.tickUtilityModule(context, tickRng);
        break;
        
      case ModuleCategory.D_NON_DETERMINISTIC:
        // Flag but attempt safe processing
        this.tickNonDeterministicModule(context, tickRng);
        break;
        
      case ModuleCategory.E_STUB:
        // Skip processing
        break;
    }
    
    // Update state hash
    this.updateStateHash();
    
    // Feed to SnapshotComposer
    this.feedSnapshotComposer();
  }
  
  private tickAREAlignedModule(context: TickSystemContext, tickRng: SeededARERng): void {
    // Module already implements TickSystem - this wrapper is just for registration
    // The actual tick logic is in the module itself
    const event = {
      type: 'are-aligned-tick',
      module: this.name,
      tick: context.tickCount,
      priority: this.priority,
      patterns: this.patternDetection,
      entropy: tickRng.nextFloat(),
    };
    this.state.deltas.push(event);
  }
  
  private tickDeterministicReadyModule(context: TickSystemContext, tickRng: SeededARERng): void {
    // Auto-generate deterministic processing
    // Uses deterministic RNG for any randomness
    const entropy = tickRng.nextFloat();
    const sequence = tickRng.nextInt(1000);
    
    const event = {
      type: 'deterministic-ready-tick',
      module: this.name,
      tick: context.tickCount,
      entropy,
      sequence,
      patterns: this.patternDetection,
      stateHash: this.state.lastHash,
    };
    
    this.state.deltas.push(event);
    
    // Track entity states if present
    this.trackEntityStates(context.tickCount);
  }
  
  private tickUtilityModule(context: TickSystemContext, tickRng: SeededARERng): void {
    // Process utility functions with deterministic RNG
    const event = {
      type: 'utility-tick',
      module: this.name,
      tick: context.tickCount,
      entropy: tickRng.nextFloat(),
    };
    this.state.deltas.push(event);
  }
  
  private tickNonDeterministicModule(context: TickSystemContext, tickRng: SeededARERng): void {
    // WARNING: This module has non-deterministic patterns
    // Log but attempt to provide deterministic fallback
    console.warn(`[AutoModuleKatalysator] WARNING: Non-deterministic module ${this.name} - using fallback`);
    
    const event = {
      type: 'non-deterministic-tick',
      module: this.name,
      tick: context.tickCount,
      entropy: tickRng.nextFloat(), // Use deterministic fallback
      warning: 'Module contains Math.random/Date.now - determinism not guaranteed',
      issues: this.patternDetection,
    };
    this.state.deltas.push(event);
  }
  
  private trackEntityStates(tickCount: number): void {
    // Track entity states for snapshot composition
    // This provides visibility into module state
    const stateSnapshot = {
      module: this.name,
      tick: tickCount,
      entityCount: this.state.entityStates.size,
      deltaCount: this.state.deltas.length,
    };
    
    // Store for snapshot
    const entityId = `auto.${this.name}` as EntityId;
    this.state.entityStates.set(entityId, stateSnapshot as unknown as Record<string, unknown>);
  }
  
  private updateStateHash(): void {
    // Generate deterministic state hash
    const content = JSON.stringify({
      module: this.name,
      tick: this.state.tickCount,
      entityCount: this.state.entityStates.size,
      deltaCount: this.state.deltas.length,
    });
    
    // Simple hash for state fingerprinting
    const hash = content.split('').reduce((h, c) => {
      return ((h << 5) - h + c.charCodeAt(0)) | 0;
    }, 0);
    
    this.state.lastHash = createStateHash(
      hash.toString(16).padStart(64, '0').slice(0, 64)
    );
  }
  
  private feedSnapshotComposer(): void {
    // Feed entity states to SnapshotComposer for PixiJS client
    try {
      for (const [entityId, state] of this.state.entityStates) {
        snapshotComposer.registerEntity(entityId, {
          position_x: 0 as KappaInt,
          position_z: 0 as KappaInt,
          health: 0 as KappaInt,
          level: 0 as KappaInt,
        });
      }
      
      // Also register module-level snapshot
      snapshotComposer.registerModuleSnapshot(this.name, {
        tick: this.state.tickCount,
        stateHash: this.state.lastHash,
        entityCount: this.state.entityStates.size,
        deltaCount: this.state.deltas.length,
        category: this.category,
        patterns: this.patternDetection,
      });
    } catch (error) {
      // SnapshotComposer may not be initialized yet - that's OK
    }
  }
  
  getState(): AutoTickSystemState {
    return this.state;
  }
  
  getModuleInfo(): { name: string; category: ModuleCategory; patterns: string[] } {
    return {
      name: this.name,
      category: this.category,
      patterns: this.patternDetection,
    };
  }
  
  onStart?(): void {
    console.log(`[AutoModuleKatalysator] Started AutoTickSystem: ${this.name} (${this.category})`);
  }
  
  onEnd?(): void {
    // Cleanup deltas periodically to prevent memory buildup
    if (this.state.deltas.length > 1000) {
      this.state.deltas = this.state.deltas.slice(-500);
    }
  }
  
  onShutdown?(): void {
    console.log(`[AutoModuleKatalysator] Shutdown AutoTickSystem: ${this.name}`);
    this.state.entityStates.clear();
    this.state.deltas = [];
  }
}

// ============================================================================
// AutoModuleKatalysator - Main System
// ============================================================================

export interface AutoModuleKatalysatorConfig {
  modulesDir?: string;
  autoPriority?: boolean;
  enableSnapshotFeed?: boolean;
  skipCategories?: ModuleCategory[];
}

export interface AutoModuleKatalysatorResult {
  totalModules: number;
  registeredSystems: Map<string, AutoGeneratedTickSystem>;
  failedModules: Map<string, string>;
  skippedModules: string[];
}

class AutoModuleKatalysatorImpl {
  private config: Required<AutoModuleKatalysatorConfig>;
  private registeredSystems: Map<string, AutoGeneratedTickSystem> = new Map();
  private failedModules: Map<string, string> = new Map();
  private moduleInfos: Map<string, ModuleInfo> = new Map();
  private initialized = false;
  
  constructor(config: AutoModuleKatalysatorConfig = {}) {
    this.config = {
      modulesDir: config.modulesDir ?? MODULES_DIR,
      autoPriority: config.autoPriority ?? true,
      enableSnapshotFeed: config.enableSnapshotFeed ?? true,
      skipCategories: config.skipCategories ?? [],
    };
  }
  
  /**
   * Initialize and scan all modules
   */
  async initialize(): Promise<AutoModuleKatalysatorResult> {
    if (this.initialized) {
      console.warn('[AutoModuleKatalysator] Already initialized');
      return this.getResult();
    }
    
    console.log('[AutoModuleKatalysator] Starting initialization...');
    console.log(`[AutoModuleKatalysator] Scanning: ${this.config.modulesDir}`);
    
    // Scan all modules
    const moduleInfos = this.scanModules();
    console.log(`[AutoModuleKatalysator] Found ${moduleInfos.size} modules`);
    
    // Categorize and process
    let registered = 0;
    let failed = 0;
    
    for (const [moduleName, info] of moduleInfos) {
      // Skip categories in skip list
      if (this.config.skipCategories.includes(info.category)) {
        console.log(`[AutoModuleKatalysator] Skipping ${moduleName} (category ${info.category})`);
        continue;
      }
      
      // Skip stubs
      if (info.category === ModuleCategory.E_STUB) {
        console.log(`[AutoModuleKatalysator] Skipping stub: ${moduleName}`);
        continue;
      }
      
      try {
        await this.registerModule(info);
        registered++;
      } catch (error) {
        this.failedModules.set(moduleName, String(error));
        failed++;
        console.error(`[AutoModuleKatalysator] Failed to register ${moduleName}:`, error);
      }
    }
    
    this.initialized = true;
    console.log(`[AutoModuleKatalysator] Initialization complete: ${registered} registered, ${failed} failed`);
    
    return this.getResult();
  }
  
  /**
   * Scan all modules in the modules directory
   */
  private scanModules(): Map<string, ModuleInfo> {
    const results = new Map<string, ModuleInfo>();
    
    if (!existsSync(this.config.modulesDir)) {
      console.error(`[AutoModuleKatalysator] Modules directory not found: ${this.config.modulesDir}`);
      return results;
    }
    
    const moduleDirs = readdirSync(this.config.modulesDir).filter(name => {
      const stat = statSync(join(this.config.modulesDir, name));
      return stat.isDirectory();
    });
    
    for (const moduleDir of moduleDirs) {
      const modulePath = join(this.config.modulesDir, moduleDir);
      
      try {
        const files = readdirSync(modulePath).filter(f => f.endsWith('.ts'));
        
        for (const file of files) {
          const filePath = join(modulePath, file);
          const info = this.analyzeModule(file, filePath, moduleDir);
          results.set(`${moduleDir}/${file}`, info);
        }
      } catch (error) {
        console.error(`[AutoModuleKatalysator] Error scanning ${moduleDir}:`, error);
      }
    }
    
    return results;
  }
  
  /**
   * Analyze a single module file
   */
  private analyzeModule(filename: string, filePath: string, moduleDir: string): ModuleInfo {
    let content = '';
    try {
      content = readFileSync(filePath, 'utf-8');
    } catch {
      content = '';
    }
    
    const lines = content.split('\n').length;
    
    // Extract imports
    const imports: string[] = [];
    const importRegex = /import\s+.*?\s+from\s+['"]([^'"]+)['"]/g;
    let match;
    while ((match = importRegex.exec(content)) !== null) {
      imports.push(match[1]);
    }
    
    // Extract exports
    const exports: string[] = [];
    const exportRegex = /export\s+(?:class|interface|type|function|const|enum)\s+(\w+)/g;
    while ((match = exportRegex.exec(content)) !== null) {
      exports.push(match[1]);
    }
    
    // Detect patterns
    const patterns: string[] = [];
    const issues: string[] = [];
    
    if (PATTERNS.TICK_SYSTEM.test(content) || PATTERNS.TICK_SYSTEM_PRIORITY.test(content)) {
      patterns.push('TICK_SYSTEM');
    }
    if (PATTERNS.DETERMINISTIC_PRNG.test(content)) {
      patterns.push('DETERMINISTIC_PRNG');
    }
    if (PATTERNS.DELTA_PATTERN.test(content)) {
      patterns.push('DELTA');
    }
    
    // Check for non-determinism
    const hasMathRandom = PATTERNS.MATH_RANDOM.test(content);
    const hasDateNow = PATTERNS.DATE_NOW_ACTUAL.test(content);
    const hasDateNewBare = PATTERNS.DATE_NEW_BARE.test(content) && !PATTERNS.DATE_NEW_WITH_ALLOW.test(content);
    const hasPerformanceNow = PATTERNS.PERFORMANCE_NOW.test(content);
    const hasAREAllow = PATTERNS.ARE_DETERMINISM_ALLOW.test(content);
    const hasTelemetrySideChannel = PATTERNS.ARE_TELEMETRY_SIDECHANNEL.test(content);
    
    if (hasMathRandom && !hasAREAllow) {
      patterns.push('MATH_RANDOM');
      issues.push('Uses Math.random - should use DeterministicPrng');
    }
    if (hasDateNow) {
      patterns.push('DATE_NOW');
      issues.push('Uses Date.now() - non-deterministic');
    }
    if (hasDateNewBare && !hasTelemetrySideChannel) {
      patterns.push('DATE_NEW');
      issues.push('Uses bare new Date()');
    }
    if (hasPerformanceNow && !hasAREAllow) {
      patterns.push('PERFORMANCE_NOW');
      issues.push('Uses performance.now()');
    }
    
    // Categorize
    const isAREAligned = PATTERNS.TICK_SYSTEM.test(content) || PATTERNS.TICK_SYSTEM_PRIORITY.test(content);
    const isStub = content.includes('return null') && lines < 30;
    
    let category: ModuleCategory;
    if (isStub) {
      category = ModuleCategory.E_STUB;
    } else if (hasMathRandom && !hasAREAllow) {
      category = ModuleCategory.D_NON_DETERMINISTIC;
    } else if (hasDateNow || (hasDateNewBare && !hasTelemetrySideChannel)) {
      category = ModuleCategory.D_NON_DETERMINISTIC;
    } else if (hasPerformanceNow && !hasAREAllow) {
      category = ModuleCategory.D_NON_DETERMINISTIC;
    } else if (isAREAligned && patterns.includes('DETERMINISTIC_PRNG')) {
      category = ModuleCategory.A_ARE_ALIGNED;
    } else if (isAREAligned || patterns.includes('DELTA')) {
      category = ModuleCategory.B_DETERMINISTIC_READY;
    } else if (patterns.length === 0) {
      category = ModuleCategory.C_UTILITY;
    } else {
      category = ModuleCategory.B_DETERMINISTIC_READY;
    }
    
    return {
      path: filePath,
      moduleName: moduleDir,
      filename,
      category,
      patterns,
      issues,
      lines,
      exports,
      imports,
    };
  }
  
  /**
   * Register a module with the TickSystemRegistry
   */
  private async registerModule(info: ModuleInfo): Promise<void> {
    // Determine priority based on module category
    const priority = this.determinePriority(info.category, info.patterns);
    
    // Create auto-generated TickSystem
    const tickSystem = new AutoGeneratedTickSystem(
      `${info.moduleName}/${info.filename}`.replace('.ts', ''),
      info.path,
      info.category,
      info.patterns,
      priority
    );
    
    // Load the target module
    await tickSystem.loadModule();
    
    // Register with TickSystemRegistry
    tickSystemRegistry.register({
      system: tickSystem,
      dependencies: this.determineDependencies(info),
      tags: [info.category, ...info.patterns],
    });
    
    // Store reference
    this.registeredSystems.set(info.path, tickSystem);
    this.moduleInfos.set(info.path, info);
    
    console.log(`[AutoModuleKatalysator] Registered: ${info.filename} (${info.category}) -> ${info.path}`);
  }
  
  /**
   * Determine TickSystem priority based on module characteristics
   */
  private determinePriority(category: ModuleCategory, patterns: string[]): TickSystemPriority {
    if (!this.config.autoPriority) {
      return TickSystemPriority.GAMEPLAY; // Default
    }
    
    // Category-based priority
    switch (category) {
      case ModuleCategory.A_ARE_ALIGNED:
        return TickSystemPriority.GAMEPLAY;
      case ModuleCategory.B_DETERMINISTIC_READY:
        return TickSystemPriority.GAMEPLAY;
      case ModuleCategory.C_UTILITY:
        return TickSystemPriority.FOUNDATION;
      case ModuleCategory.D_NON_DETERMINISTIC:
        return TickSystemPriority.PERSISTENCE; // Lower priority for non-deterministic
      default:
        return TickSystemPriority.GAMEPLAY;
    }
  }
  
  /**
   * Determine module dependencies based on imports
   */
  private determineDependencies(info: ModuleInfo): string[] {
    const deps: string[] = [];
    
    // Check imports for known system dependencies
    for (const imp of info.imports) {
      if (imp.includes('combat')) deps.push('combat-system');
      if (imp.includes('npc')) deps.push('npc-system');
      if (imp.includes('player')) deps.push('player-system');
      if (imp.includes('economy')) deps.push('economy-system');
      if (imp.includes('quest')) deps.push('quest-system');
      if (imp.includes('guild')) deps.push('guild-system');
    }
    
    // Add default dependencies for Category B and higher
    if (info.category === ModuleCategory.A_ARE_ALIGNED || 
        info.category === ModuleCategory.B_DETERMINISTIC_READY) {
      deps.push('player-system'); // Most systems depend on player
    }
    
    return [...new Set(deps)]; // Deduplicate
  }
  
  /**
   * Get the initialization result
   */
  getResult(): AutoModuleKatalysatorResult {
    return {
      totalModules: this.moduleInfos.size,
      registeredSystems: this.registeredSystems,
      failedModules: this.failedModules,
      skippedModules: Array.from(this.moduleInfos.values())
        .filter(m => m.category === ModuleCategory.E_STUB)
        .map(m => m.path),
    };
  }
  
  /**
   * Get status of all registered systems
   */
  getStatus(): {
    total: number;
    registered: number;
    failed: number;
    byCategory: Record<ModuleCategory, number>;
    systems: Array<{ name: string; category: ModuleCategory; enabled: boolean; tickCount: number }>;
  } {
    const byCategory: Record<ModuleCategory, number> = {
      [ModuleCategory.A_ARE_ALIGNED]: 0,
      [ModuleCategory.B_DETERMINISTIC_READY]: 0,
      [ModuleCategory.C_UTILITY]: 0,
      [ModuleCategory.D_NON_DETERMINISTIC]: 0,
      [ModuleCategory.E_STUB]: 0,
    };
    
    const systems: Array<{ name: string; category: ModuleCategory; enabled: boolean; tickCount: number }> = [];
    
    for (const [path, system] of this.registeredSystems) {
      const info = this.moduleInfos.get(path);
      if (info) {
        byCategory[info.category]++;
      }
      systems.push({
        name: system.name,
        category: system.category,
        enabled: system.enabled,
        tickCount: system.getState().tickCount,
      });
    }
    
    return {
      total: this.moduleInfos.size,
      registered: this.registeredSystems.size,
      failed: this.failedModules.size,
      byCategory,
      systems,
    };
  }
  
  /**
   * Get a specific registered system
   */
  getSystem(name: string): AutoGeneratedTickSystem | undefined {
    for (const system of this.registeredSystems.values()) {
      if (system.name === name) {
        return system;
      }
    }
    return undefined;
  }
  
  /**
   * Enable/disable a specific system
   */
  setSystemEnabled(name: string, enabled: boolean): boolean {
    const system = this.getSystem(name);
    if (system) {
      system.enabled = enabled;
      return true;
    }
    return false;
  }
  
  /**
   * Reset and reinitialize
   */
  async reset(): Promise<AutoModuleKatalysatorResult> {
    this.registeredSystems.clear();
    this.failedModules.clear();
    this.moduleInfos.clear();
    this.initialized = false;
    
    return this.initialize();
  }
}

// ============================================================================
// Singleton Export
// ============================================================================

export const autoModuleKatalysator = new AutoModuleKatalysatorImpl();

export function createAutoModuleKatalysator(
  config?: AutoModuleKatalysatorConfig
): AutoModuleKatalysatorImpl {
  return new AutoModuleKatalysatorImpl(config);
}

// Re-export for convenience
export type { AutoTickSystemState } from './AutoGeneratedTickSystem';
export { AutoGeneratedTickSystem } from './AutoGeneratedTickSystem';