pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "ArelorianAlpha"
include ':app'
include ':capacitor-android'
project(':capacitor-android').projectDir = new File(rootDir, './capacitor-android/capacitor-android')