// @ARE-GUARD-EXEMPT: non-sim module
/**
 * Chat channel types shared across the 3-channel chat system.
 *
 * - local:  proximity-based; only entities within range see the message
 * - global: server-wide broadcast; everyone sees it
 * - status: auto-generated by the engine; read-only; proximity-scoped
 */

export type ChatChannel = "local" | "global" | "status";

export type SenderType = "player" | "npc" | "system";

export interface ChannelChatMessage {
  id: string;
  channel: ChatChannel;
  senderType: SenderType;
  senderId: string;
  senderName: string;
  npcId?: string;
  text: string;
  ts: number;
  /** Position of sender at time of message (for proximity filtering). */
  position?: { x: number; y: number; z?: number };
}

/** Default proximity radius for local and status channels (world units). */
export const LOCAL_CHAT_RADIUS = 50;
