/**
 * generate-home.mjs
 * Generates the wiki Home page with automatic structure
 */

import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

/**
 * Generate the Home.md for GitHub Wiki
 * @param {Object} options
 * @returns {string}
 */
export function generateHomePage(options = {}) {
  const {
    projectName = 'Areloria',
    projectTagline = 'Deterministic Browser MMORPG Engine',
    wikiSourceDir = './docs/wiki',
    repoUrl = '',
    version = '1.0.0'
  } = options;
  
  const today = new Date().toISOString().split('T')[0];
  
  const lines = [
    '# ' + projectName + ' \u2014 Living World Wiki',
    '',
    '> **Autonomous Codex Engine** | Generated from project knowledge',
    '',
    projectTagline,
    '',
    '---',
    '',
    '## Vision',
    '',
    'Areloria is a deterministic browser MMORPG built around a 10Hz logic engine, autonomous NPC society, procedural world growth and the ARE Logic simulation model.',
    '',
    'The world is designed to feel **inhabited rather than scripted**. NPCs are future citizens, workers, traders, political actors, enemies, allies, and memory-bearing participants in a simulated civilization.',
    '',
    '---',
    '',
    '## Core Pillars',
    '',
    '| Pillar | Description |',
    '|--------|-------------|',
    '| **Deterministic 10Hz Simulation** | Server tick at 100ms intervals, every state reproducible |',
    '| **Browser-First MMORPG** | Three.js/WebGL and PixiJS clients, no installation |',
    '| **Autonomous NPC Society** | Memory, trade, politics, governance, rebellion |',
    '| **Procedural World Expansion** | Chunk-based streaming, emergent settlements |',
    '| **Self-Healing Infrastructure** | AST repair, runtime integrity guards |',
    '| **ARE Kernel / Ouroboros Loop** | Axiomatic rule system for bounded emergence |',
    '',
    '---',
    '',
    '## Start Here',
    '',
    '| Quick Path | Page | Description |',
    '|------------|------|-------------|',
    '| Quick Start | [README.md](' + repoUrl + ') | Setup and first steps |',
    '| Gameplay | [docs/GAME_DATA_MANIFEST.md](' + repoUrl + '/docs/GAME_DATA_MANIFEST.md) | Core gameplay systems |',
    '| Architecture | [docs/ARCHITECTURE_NOTE.md](' + repoUrl + '/docs/ARCHITECTURE_NOTE.md) | System architecture |',
    '| NPC Society | [docs/NPC_SYSTEM.md](' + repoUrl + '/docs/NPC_SYSTEM.md) | Autonomous NPCs |',
    '| World Generation | [docs/WORLD_GENERATION.md](' + repoUrl + '/docs/WORLD_GENERATION.md) | Procedural world |',
    '| Deployment | [DEPLOYMENT.md](' + repoUrl + '/DEPLOYMENT.md) | VPS and Docker deploy |',
    '| Roadmap | [docs/ROADMAP_TO_RELEASE.md](' + repoUrl + '/docs/ROADMAP_TO_RELEASE.md) | What\'s next |',
    '| Glossary | [Glossary](Glossary) | Key terms |',
    '',
    '---',
    '',
    '## Technical Architecture',
    '',
    '```',
    'CLIENT LAYER',
    '  3D Client (Babylon.js) | 2D Client (PixiJS v7 + React)',
    '',
    'TRANSPORT LAYER',
    '  WebSocket (ws)',
    '',
    'SERVER LAYER (10Hz)',
    '  WorldTick (100ms tick) | ARE Determinism Gate',
    '',
    'PERSISTENCE LAYER',
    '  Supabase/PostgreSQL | Redis (optional) | JSON Fallback',
    '```',
    '',
    '---',
    '',
    '## Key Systems',
    '',
    '### ARE Logic Core',
    '',
    'The **Authentic Reality Emancipation (ARE)** logic model governs:',
    '',
    '- Deterministic time (`AREClock`)',
    '- Deterministic randomness (`ARERng`)',
    '- World pressure and causal mutation',
    '- Region and chunk rule enforcement',
    '- Oracle/brain interpretation',
    '',
    'See: [ARE-Logic-Core](ARE-Logic-Core) | [ARE-Erdos Attractor Model](ARE-Erdos-Attractor-Model) | [Determinism](Determinism)',
    '',
    '### World Simulation',
    '',
    '- **10Hz Tick Loop** \u2014 Every 100ms, the server advances simulation state',
    '- **Observation-Driven** \u2014 Unobserved regions sleep or decay',
    '- **Protected Structures** \u2014 Player-built content is protected by default',
    '- **Manifest System** \u2014 Deterministic state hash chain for client sync',
    '',
    '### Autonomous NPCs',
    '',
    'NPCs can:',
    '- Remember local events and player actions',
    '- Trade and price goods based on scarcity',
    '- Participate in politics, elections, wars',
    '- Found or join settlements',
    '- Rebel against oppressive rulers',
    '',
    '---',
    '',
    '## Documentation Map',
    '',
    '### Core Documentation',
    '',
    '| Area | File | Purpose |',
    '|------|------|---------|',
    '| Project Status | [docs/PROJECT_STATUS_2026.md](' + repoUrl + '/docs/PROJECT_STATUS_2026.md) | Current implementation state |',
    '| Agent Rules | [AGENTS.md](' + repoUrl + '/AGENTS.md) | AI agent guidelines |',
    '| Determinism | [docs/ARE_DETERMINISM_CLASSIFICATION.md](' + repoUrl + '/docs/ARE_DETERMINISM_CLASSIFICATION.md) | Determinism requirements |',
    '',
    '### Gameplay Systems',
    '',
    '| System | Status | Key Files |',
    '|--------|--------|-----------|',
    '| Combat | Implemented | server/src/modules/combat/ |',
    '| NPCs | Implemented | server/src/modules/npc/ |',
    '| Inventory | Implemented | server/src/modules/inventory/ |',
    '| Quests | Implemented | server/src/modules/quest/ |',
    '| Crafting | Implemented | server/src/modules/crafting/ |',
    '| Warfront | Implemented | server/src/modules/warfront/ |',
    '',
    '---',
    '',
    '## Contributing',
    '',
    '1. **Small PRs only** \u2014 Changes should be focused and reviewable',
    '2. **Determinism first** \u2014 New simulation code must pass ARE gate',
    '3. **Test coverage** \u2014 Add tests for new systems',
    '4. **Documentation** \u2014 Update wiki when changing systems',
    '5. **No lockfile churn** \u2014 Keep PRs focused',
    '',
    'See: [docs/AGENT_FEATURE_PR_POLICY.md](' + repoUrl + '/docs/AGENT_FEATURE_PR_POLICY.md)',
    '',
    '---',
    '',
    '## Quick Reference',
    '',
    '```bash',
    '# Setup',
    'pnpm install',
    '',
    '# Development',
    'npx tsx server/src/index.ts  # Start server with Vite middleware',
    '',
    '# Build',
    'pnpm run build',
    '',
    '# Test',
    'pnpm run test',
    '```',
    '',
    '---',
    '',
    '**Status:** Living Wiki \u2014 Auto-generated from project knowledge',
    '**Last Updated:** ' + today,
    '**Version:** ' + version,
    ''
  ];
  
  return lines.join('\n');
}