/**
 * stitchAssetManifest.ts
 *
 * Client-side Stitch 2.5D asset registry for Areloria/WASD.
 * 
 * Generated by: scripts/stitch-atlas-intake.py
 * Deterministic: No Math.random, no Date.now, no UUIDs for asset IDs.
 */

export type StitchAssetCategory =
  | "enemy"
  | "boss"
  | "hero"
  | "npc"
  | "vfx"
  | "tile"
  | "prop"
  | "item"
  | "equipment_overlay"
  | "ui"
  | "unknown";

export interface StitchPivot {
  x: number;
  y: number;
}

export interface StitchRuntimeAsset {
  assetId: string;
  category: StitchAssetCategory;
  displayName: string;
  sourcePath: string;
  imagePath: string;
  atlasPath: string;
  previewPath: string;
  width: number;
  height: number;
  frameWidth: number;
  frameHeight: number;
  columns: number;
  rows: number;
  frameCount: number;
  pivot: StitchPivot;
  tags: string[];
  sourceSha256: string;
  processedSha256: string;
  status: "accepted";
}

export interface StitchQuarantineEntry {
  assetId: string;
  sourcePath: string;
  reason: string;
  warnings: string[];
}

export interface StitchRuntimeManifest {
  schemaVersion: number;
  packId: string;
  generatedBy: string;
  deterministic: boolean;
  assets: StitchRuntimeAsset[];
  quarantine: StitchQuarantineEntry[];
}

// Default pivot values by category
const PIVOT_BY_CATEGORY: Record<StitchAssetCategory, StitchPivot> = {
  enemy: { x: 0.5, y: 0.82 },
  boss: { x: 0.5, y: 0.82 },
  hero: { x: 0.5, y: 0.82 },
  npc: { x: 0.5, y: 0.82 },
  vfx: { x: 0.5, y: 0.5 },
  tile: { x: 0.5, y: 0.5 },
  prop: { x: 0.5, y: 0.9 },
  item: { x: 0.5, y: 0.5 },
  equipment_overlay: { x: 0.5, y: 0.5 },
  ui: { x: 0.5, y: 0.5 },
  unknown: { x: 0.5, y: 0.5 },
};

// Sample asset IDs for demo/preview (stable, deterministic)
const SAMPLE_ENEMY_ID = "stitch_enemy_skeleton_warrior";
const SAMPLE_TILE_ID = "stitch_tile_crypt_floor";
const SAMPLE_VFX_ID = "stitch_vfx_magic_burst";
const SAMPLE_PROP_ID = "stitch_prop_infernal_gate";

/**
 * Fetch the Stitch runtime manifest from the client assets directory.
 */
export async function fetchStitchManifest(): Promise<StitchRuntimeManifest | null> {
  try {
    const res = await fetch("/2d-assets/stitch/manifest.json", {
      cache: "no-store",
    });
    if (!res.ok) {
      console.warn("[StitchAssetManifest] Failed to load manifest:", res.status);
      return null;
    }
    return (await res.json()) as StitchRuntimeManifest;
  } catch (err) {
    console.warn("[StitchAssetManifest] Error loading manifest:", err);
    return null;
  }
}

/**
 * Get a single asset by its deterministic assetId.
 */
export function getStitchAssetById(
  manifest: StitchRuntimeManifest,
  assetId: string
): StitchRuntimeAsset | undefined {
  return manifest.assets.find((a) => a.assetId === assetId);
}

/**
 * Get all assets in a specific category.
 */
export function getStitchAssetsByCategory(
  manifest: StitchRuntimeManifest,
  category: StitchAssetCategory
): StitchRuntimeAsset[] {
  return manifest.assets.filter((a) => a.category === category);
}

/**
 * Get the first available asset for a category (fallback for missing samples).
 */
export function getFirstAssetByCategory(
  manifest: StitchRuntimeManifest,
  category: StitchAssetCategory
): StitchRuntimeAsset | undefined {
  const assets = getStitchAssetsByCategory(manifest, category);
  return assets.length > 0 ? assets[0] : undefined;
}

/**
 * Get a default enemy sprite for preview/testing.
 * Uses first enemy if exact ID not found.
 */
export function getDefaultEnemySprite(
  manifest: StitchRuntimeManifest
): StitchRuntimeAsset | undefined {
  const exact = getStitchAssetById(manifest, SAMPLE_ENEMY_ID);
  if (exact) return exact;
  return getFirstAssetByCategory(manifest, "enemy");
}

/**
 * Get a default tile sprite for preview/testing.
 */
export function getDefaultTileSprite(
  manifest: StitchRuntimeManifest
): StitchRuntimeAsset | undefined {
  const exact = getStitchAssetById(manifest, SAMPLE_TILE_ID);
  if (exact) return exact;
  return getFirstAssetByCategory(manifest, "tile");
}

/**
 * Get a default VFX sprite for preview/testing.
 */
export function getDefaultVfxSprite(
  manifest: StitchRuntimeManifest
): StitchRuntimeAsset | undefined {
  const exact = getStitchAssetById(manifest, SAMPLE_VFX_ID);
  if (exact) return exact;
  return getFirstAssetByCategory(manifest, "vfx");
}

/**
 * Get a default prop sprite for preview/testing.
 */
export function getDefaultPropSprite(
  manifest: StitchRuntimeManifest
): StitchRuntimeAsset | undefined {
  const exact = getStitchAssetById(manifest, SAMPLE_PROP_ID);
  if (exact) return exact;
  return getFirstAssetByCategory(manifest, "prop");
}

/**
 * Build a full URL for an asset image.
 */
export function stitchImageUrl(manifest: StitchRuntimeManifest, asset: StitchRuntimeAsset): string {
  return `/2d-assets/stitch/${asset.imagePath}`;
}

/**
 * Build a full URL for an atlas JSON.
 */
export function stitchAtlasUrl(manifest: StitchRuntimeManifest, asset: StitchRuntimeAsset): string {
  return `/2d-assets/stitch/${asset.atlasPath}`;
}

/**
 * Get pivot for a category (for rendering).
 */
export function getPivotForCategory(category: StitchAssetCategory): StitchPivot {
  return PIVOT_BY_CATEGORY[category] ?? { x: 0.5, y: 0.5 };
}

/**
 * Count assets by category.
 */
export function countByCategory(manifest: StitchRuntimeManifest): Record<StitchAssetCategory, number> {
  const counts: Record<string, number> = {};
  for (const asset of manifest.assets) {
    counts[asset.category] = (counts[asset.category] ?? 0) + 1;
  }
  return counts as Record<StitchAssetCategory, number>;
}

/**
 * Summary stats for the manifest.
 */
export interface StitchManifestStats {
  totalAssets: number;
  totalFrames: number;
  categories: Record<StitchAssetCategory, number>;
  quarantinedCount: number;
}

export function getManifestStats(manifest: StitchRuntimeManifest): StitchManifestStats {
  const categories = countByCategory(manifest);
  const totalFrames = manifest.assets.reduce((sum, a) => sum + a.frameCount, 0);
  return {
    totalAssets: manifest.assets.length,
    totalFrames,
    categories,
    quarantinedCount: manifest.quarantine.length,
  };
}