/**
 * stitchAssetManifest.ts
 *
 * Client-side Stitch 2.5D asset registry for Areloria/WASD.
 *
 * Generated by: scripts/stitch_atlas_intake.py
 * Deterministic: No Math.random, no Date.now, no UUIDs for asset IDs.
 *
 * Runtime rule:
 * - assets[] are accepted runtime assets.
 * - manualReview[] and referenceOnly[] are visible to tooling only.
 * - manualReview/referenceOnly entries must never be rendered as gameplay sprites.
 */

export type StitchAssetCategory =
  | "enemy"
  | "boss"
  | "hero"
  | "npc"
  | "vfx"
  | "tile"
  | "building"
  | "prop"
  | "item"
  | "equipment_overlay"
  | "ui"
  | "unknown";

export interface StitchPivot {
  readonly x: number;
  readonly y: number;
}

export interface StitchRuntimeAsset {
  readonly assetId: string;
  readonly category: StitchAssetCategory;
  readonly displayName: string;
  readonly sourcePath: string;
  readonly imagePath: string;
  readonly atlasPath: string;
  readonly previewPath: string;
  readonly width: number;
  readonly height: number;
  readonly frameWidth: number;
  readonly frameHeight: number;
  readonly columns: number;
  readonly rows: number;
  readonly frameCount: number;
  readonly pivot: StitchPivot;
  readonly tags: readonly string[];
  readonly sourceSha256: string;
  readonly processedSha256: string;
  readonly status: "accepted";
}

export interface StitchReviewEntry {
  readonly assetId: string;
  readonly category: StitchAssetCategory;
  readonly sourcePath: string;
  readonly warnings: readonly string[];
  readonly sourceSha256: string;
}

export interface StitchQuarantineEntry {
  readonly assetId: string;
  readonly category?: StitchAssetCategory;
  readonly sourcePath: string;
  readonly reason: string;
  readonly warnings: readonly string[];
  readonly sourceSha256?: string;
}

export interface StitchRuntimeManifest {
  readonly schemaVersion: number;
  readonly packId: string;
  readonly generatedBy: string;
  readonly deterministic: boolean;
  readonly assetCount?: number;
  readonly manualReviewCount?: number;
  readonly referenceOnlyCount?: number;
  readonly quarantineCount?: number;
  readonly assets: readonly StitchRuntimeAsset[];
  readonly manualReview?: readonly StitchReviewEntry[];
  readonly referenceOnly?: readonly StitchReviewEntry[];
  readonly quarantine: readonly StitchQuarantineEntry[];
}

export interface StitchManifestStats {
  readonly totalAssets: number;
  readonly totalFrames: number;
  readonly categories: Record<StitchAssetCategory, number>;
  readonly quarantinedCount: number;
  readonly manualReviewCount: number;
  readonly referenceOnlyCount: number;
}

const PIVOT_BY_CATEGORY: Record<StitchAssetCategory, StitchPivot> = {
  enemy: { x: 0.5, y: 0.82 },
  boss: { x: 0.5, y: 0.82 },
  hero: { x: 0.5, y: 0.82 },
  npc: { x: 0.5, y: 0.82 },
  vfx: { x: 0.5, y: 0.5 },
  tile: { x: 0.5, y: 0.5 },
  building: { x: 0.5, y: 0.9 },
  prop: { x: 0.5, y: 0.9 },
  item: { x: 0.5, y: 0.5 },
  equipment_overlay: { x: 0.5, y: 0.5 },
  ui: { x: 0.5, y: 0.5 },
  unknown: { x: 0.5, y: 0.5 },
};

const KNOWN_CATEGORIES = new Set<StitchAssetCategory>([
  "enemy",
  "boss",
  "hero",
  "npc",
  "vfx",
  "tile",
  "building",
  "prop",
  "item",
  "equipment_overlay",
  "ui",
  "unknown",
]);

// Sample asset IDs for demo/preview (stable, deterministic).
// Fallback helpers still use first accepted category asset if exact sample is absent.
const SAMPLE_ENEMY_ID = "stitch_enemy_undead_blade_walker_square_sheet";
const SAMPLE_TILE_ID = "stitch_tile_swamp_marsh_biome_tiles_props_backgrounds_sheet";
const SAMPLE_VFX_ID = "stitch_vfx_arelorian_elemental_spell_fx_square_sheet";
const SAMPLE_PROP_ID = "stitch_prop_eldritch_modular_gothic_dungeon_assets_catalog";

function asRecord(value: unknown): Record<string, unknown> | null {
  return value && typeof value === "object" ? (value as Record<string, unknown>) : null;
}

function asString(value: unknown, fallback = ""): string {
  return typeof value === "string" ? value : fallback;
}

function asNumber(value: unknown, fallback = 0): number {
  return typeof value === "number" && Number.isFinite(value) ? value : fallback;
}

function asStringArray(value: unknown): readonly string[] {
  return Array.isArray(value)
    ? value.filter((item): item is string => typeof item === "string")
    : [];
}

function normalizeCategory(value: unknown): StitchAssetCategory {
  const raw = asString(value, "unknown") as StitchAssetCategory;
  return KNOWN_CATEGORIES.has(raw) ? raw : "unknown";
}

function normalizePivot(value: unknown, category: StitchAssetCategory): StitchPivot {
  const record = asRecord(value);

  if (!record) {
    return getPivotForCategory(category);
  }

  return {
    x: asNumber(record.x, getPivotForCategory(category).x),
    y: asNumber(record.y, getPivotForCategory(category).y),
  };
}

function normalizeRuntimeAsset(value: unknown): StitchRuntimeAsset | null {
  const record = asRecord(value);
  if (!record) return null;

  const assetId = asString(record.assetId);
  const imagePath = asString(record.imagePath);
  const atlasPath = asString(record.atlasPath);
  const previewPath = asString(record.previewPath);

  if (!assetId || !imagePath || !atlasPath || !previewPath) {
    return null;
  }

  const category = normalizeCategory(record.category);

  return {
    assetId,
    category,
    displayName: asString(record.displayName, assetId.replace(/_/g, " ")),
    sourcePath: asString(record.sourcePath),
    imagePath,
    atlasPath,
    previewPath,
    width: asNumber(record.width),
    height: asNumber(record.height),
    frameWidth: asNumber(record.frameWidth),
    frameHeight: asNumber(record.frameHeight),
    columns: asNumber(record.columns),
    rows: asNumber(record.rows),
    frameCount: asNumber(record.frameCount),
    pivot: normalizePivot(record.pivot, category),
    tags: asStringArray(record.tags),
    sourceSha256: asString(record.sourceSha256),
    processedSha256: asString(record.processedSha256),
    status: "accepted",
  };
}

function normalizeReviewEntry(value: unknown): StitchReviewEntry | null {
  const record = asRecord(value);
  if (!record) return null;

  const assetId = asString(record.assetId);
  const sourcePath = asString(record.sourcePath);

  if (!assetId || !sourcePath) {
    return null;
  }

  return {
    assetId,
    category: normalizeCategory(record.category),
    sourcePath,
    warnings: asStringArray(record.warnings),
    sourceSha256: asString(record.sourceSha256),
  };
}

function normalizeQuarantineEntry(value: unknown): StitchQuarantineEntry | null {
  const record = asRecord(value);
  if (!record) return null;

  const assetId = asString(record.assetId);
  const sourcePath = asString(record.sourcePath);

  if (!assetId || !sourcePath) {
    return null;
  }

  return {
    assetId,
    category: record.category === undefined ? undefined : normalizeCategory(record.category),
    sourcePath,
    reason: asString(record.reason, "not_processable"),
    warnings: asStringArray(record.warnings),
    sourceSha256: asString(record.sourceSha256),
  };
}

export function normalizeStitchManifest(raw: unknown): StitchRuntimeManifest | null {
  const record = asRecord(raw);
  if (!record) return null;

  const assets = Array.isArray(record.assets)
    ? record.assets.map(normalizeRuntimeAsset).filter((asset): asset is StitchRuntimeAsset => asset !== null)
    : [];

  const manualReview = Array.isArray(record.manualReview)
    ? record.manualReview.map(normalizeReviewEntry).filter((entry): entry is StitchReviewEntry => entry !== null)
    : [];

  const referenceOnly = Array.isArray(record.referenceOnly)
    ? record.referenceOnly.map(normalizeReviewEntry).filter((entry): entry is StitchReviewEntry => entry !== null)
    : [];

  const quarantine = Array.isArray(record.quarantine)
    ? record.quarantine.map(normalizeQuarantineEntry).filter((entry): entry is StitchQuarantineEntry => entry !== null)
    : [];

  return {
    schemaVersion: asNumber(record.schemaVersion, 1),
    packId: asString(record.packId, "unknown_stitch_pack"),
    generatedBy: asString(record.generatedBy, "scripts/stitch_atlas_intake.py"),
    deterministic: record.deterministic === true,
    assetCount: asNumber(record.assetCount, assets.length),
    manualReviewCount: asNumber(record.manualReviewCount, manualReview.length),
    referenceOnlyCount: asNumber(record.referenceOnlyCount, referenceOnly.length),
    quarantineCount: asNumber(record.quarantineCount, quarantine.length),
    assets,
    manualReview,
    referenceOnly,
    quarantine,
  };
}

/**
 * Fetch the Stitch runtime manifest from the client assets directory.
 */
export async function fetchStitchManifest(): Promise<StitchRuntimeManifest | null> {
  try {
    const res = await fetch("/2d-assets/stitch/manifest.json", {
      cache: "no-store",
    });

    if (!res.ok) {
      console.warn("[StitchAssetManifest] Failed to load manifest:", res.status);
      return null;
    }

    return normalizeStitchManifest(await res.json());
  } catch (err) {
    console.warn("[StitchAssetManifest] Error loading manifest:", err);
    return null;
  }
}

/**
 * Get a single accepted runtime asset by its deterministic assetId.
 */
export function getStitchAssetById(
  manifest: StitchRuntimeManifest,
  assetId: string,
): StitchRuntimeAsset | undefined {
  return manifest.assets.find((asset) => asset.assetId === assetId);
}

/**
 * Get all accepted runtime assets in a specific category.
 */
export function getStitchAssetsByCategory(
  manifest: StitchRuntimeManifest,
  category: StitchAssetCategory,
): StitchRuntimeAsset[] {
  return [...manifest.assets]
    .filter((asset) => asset.category === category)
    .sort((a, b) => a.assetId.localeCompare(b.assetId));
}

/**
 * Get the first accepted asset for a category. Deterministic by assetId.
 */
export function getFirstAssetByCategory(
  manifest: StitchRuntimeManifest,
  category: StitchAssetCategory,
): StitchRuntimeAsset | undefined {
  return getStitchAssetsByCategory(manifest, category)[0];
}

export function getManualReviewEntries(manifest: StitchRuntimeManifest): readonly StitchReviewEntry[] {
  return [...(manifest.manualReview ?? [])].sort((a, b) => a.assetId.localeCompare(b.assetId));
}

export function getReferenceOnlyEntries(manifest: StitchRuntimeManifest): readonly StitchReviewEntry[] {
  return [...(manifest.referenceOnly ?? [])].sort((a, b) => a.assetId.localeCompare(b.assetId));
}

export function getQuarantineEntries(manifest: StitchRuntimeManifest): readonly StitchQuarantineEntry[] {
  return [...manifest.quarantine].sort((a, b) => a.assetId.localeCompare(b.assetId));
}

/**
 * Get a default enemy sprite for preview/testing.
 * Uses first accepted enemy if exact ID is absent.
 */
export function getDefaultEnemySprite(
  manifest: StitchRuntimeManifest,
): StitchRuntimeAsset | undefined {
  const exact = getStitchAssetById(manifest, SAMPLE_ENEMY_ID);
  if (exact) return exact;
  return getFirstAssetByCategory(manifest, "enemy");
}

/**
 * Get a default tile sprite for preview/testing.
 */
export function getDefaultTileSprite(
  manifest: StitchRuntimeManifest,
): StitchRuntimeAsset | undefined {
  const exact = getStitchAssetById(manifest, SAMPLE_TILE_ID);
  if (exact) return exact;
  return getFirstAssetByCategory(manifest, "tile");
}

/**
 * Get a default VFX sprite for preview/testing.
 */
export function getDefaultVfxSprite(
  manifest: StitchRuntimeManifest,
): StitchRuntimeAsset | undefined {
  const exact = getStitchAssetById(manifest, SAMPLE_VFX_ID);
  if (exact) return exact;
  return getFirstAssetByCategory(manifest, "vfx");
}

/**
 * Get a default prop sprite for preview/testing.
 */
export function getDefaultPropSprite(
  manifest: StitchRuntimeManifest,
): StitchRuntimeAsset | undefined {
  const exact = getStitchAssetById(manifest, SAMPLE_PROP_ID);
  if (exact) return exact;
  return getFirstAssetByCategory(manifest, "prop");
}

export function getDefaultBuildingSprite(
  manifest: StitchRuntimeManifest,
): StitchRuntimeAsset | undefined {
  return getFirstAssetByCategory(manifest, "building");
}

/**
 * Build a full URL for an asset image.
 */
export function stitchImageUrl(_manifest: StitchRuntimeManifest, asset: StitchRuntimeAsset): string {
  return `/2d-assets/stitch/${asset.imagePath}`;
}

/**
 * Build a full URL for an atlas JSON.
 */
export function stitchAtlasUrl(_manifest: StitchRuntimeManifest, asset: StitchRuntimeAsset): string {
  return `/2d-assets/stitch/${asset.atlasPath}`;
}

/**
 * Get pivot for a category.
 */
export function getPivotForCategory(category: StitchAssetCategory): StitchPivot {
  return PIVOT_BY_CATEGORY[category] ?? PIVOT_BY_CATEGORY.unknown;
}

/**
 * Count accepted runtime assets by category.
 */
export function countByCategory(manifest: StitchRuntimeManifest): Record<StitchAssetCategory, number> {
  const counts = Object.fromEntries(
    [...KNOWN_CATEGORIES].map((category) => [category, 0]),
  ) as Record<StitchAssetCategory, number>;

  for (const asset of manifest.assets) {
    counts[asset.category] += 1;
  }

  return counts;
}

/**
 * Summary stats for the accepted runtime manifest plus review queues.
 */
export function getManifestStats(manifest: StitchRuntimeManifest): StitchManifestStats {
  const categories = countByCategory(manifest);
  const totalFrames = manifest.assets.reduce((sum, asset) => sum + asset.frameCount, 0);

  return {
    totalAssets: manifest.assets.length,
    totalFrames,
    categories,
    quarantinedCount: manifest.quarantineCount ?? manifest.quarantine.length,
    manualReviewCount: manifest.manualReviewCount ?? manifest.manualReview?.length ?? 0,
    referenceOnlyCount: manifest.referenceOnlyCount ?? manifest.referenceOnly?.length ?? 0,
  };
}
