import React from 'react';

interface ArelorianProjectBriefProps {
  className?: string;
}

export function ArelorianProjectBrief({ className = '' }: ArelorianProjectBriefProps) {
  const content = `# Project Brief: ARELORIAN ## 1. Vision Statement **ARELORIAN** is a high-fidelity mobile/tablet MMORPG that fuses mystical fantasy with a sharp, 'Cyber-Zen' aesthetic. The experience is defined by its "Diamond Glass" UIâa visual language of crystalline textures, high-transparency frosted glass effects, and vibrant energy flows. ## 2. Visual Identity (Cyber-Zen) * **Design Philosophy**: "Diamond Glass" â sharp crystalline edges, milky transparency, and 2.5D depth. * **Color Palette**: * **Primary**: Deep Marine Darkblue (#101419) - The void-like foundation. * **Secondary**: Sunset-Orange (#FF7A00) - Action, urgency, and primary interaction. * **Accent**: Neon-Green Shine (#2AE500) - Positive status, health, and skill progression. * **Tertiary**: Mana-Cyan (#00E5FF) - Magic, navigation, and world status. * **Typography**: Clean, sans-serif (Epilogue) with wide tracking for headlines to evoke a futuristic, spacious feel. * **Branding**: The central Ouroboros (fire snake) logo encased in a multifaceted diamond frame. ## 3. Core Gameplay Pillars * **Classless Progression**: A RuneScape-inspired skill system with no level cap. Players master diverse combat (Sword, Axe, Shield, Spear, Dagger, Magic, Knuckle, Bow) and gathering/crafting (Mining, Blacksmithing, Woodcutting) professions. * **Strategic Equipment**: A "Paperdoll" system similar to World of Warcraft, where equipment choice and visual representation are central to character identity. * **Dynamic World**: Real-time interaction with chunks, factions (Azure Sanctum, Solar Exiles, Void Walkers), and an evolving questline centered on the Ouroboros lore. * **Social & Alliance**: Strong emphasis on Guild progression and faction standing. ## 4. UI Architecture & Flow 1. **Boot & Authentication**: Seamless transition from Splash (Logo/Loading Sigil) to Login (Session Resume/Guest Entry). 2. **Identity Management**: Character Selection with portal-view slots and detailed Attribute Matrix for stat distribution. 3. **Active Gameplay (HUD)**: * **Navigation**: Isometric Mini-map and full World Map. * **Interaction**: Diamond-style interaction prompts for NPCs and world objects. * **Combat**: Hexagonal action bars for primary/secondary skill execution. 4. **Information Management**: * **Inventory**: 30-slot grid with high-detail item tooltips. * **Quest Journal**: Dual-pane management of active/available story arcs. ## 5. Technical Specification (UI Layer) * **Render Path**: \`main.tsx\` â \`DeterministicWorldIsoApp.tsx\` â \`ArelorianStitchHud.tsx\` â \`UIOverlayLayer.tsx\`. * **Mobile-First Controls**: Deterministic MobileMovePad (bottom-left) and context-aware action triggers (bottom-right). * **Persistence**: Real-time Server Sync status indicator (Footer) for local/fallback data management.`;
  return (
    <div className={className} dangerouslySetInnerHTML={{ __html: content }} />
  );
}
