on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - name: npm install and test
        run: |
          npm install
          npm run test --if-present
      
      - name: Install client dependencies
        run: npm install --prefix client
      
      - name: Build
        run: |
          npm run build --prefix client
          npm run build --prefix server
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: wasd-build-artifact
          path: .
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: wasd-build-artifact
          path: .
